# PizzaG Custom Prebuilt App Additions

LOCAL_PATH:= $(call my-dir)

# Nova Launcher
include $(CLEAR_VARS)
LOCAL_MODULE := NovaLauncher
LOCAL_SRC_FILES := app/NovaLauncher/NovaLauncher.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

# PdaNet Plus
include $(CLEAR_VARS)
LOCAL_MODULE := PdaNetPlus
LOCAL_SRC_FILES := app/PdaNetPlus/PdaNetPlus.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

# X-Plore File Manager
include $(CLEAR_VARS)
LOCAL_MODULE := Xplore
LOCAL_SRC_FILES := app/Xplore/Xplore.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

# Gboard
include $(CLEAR_VARS)
LOCAL_MODULE := LatinIMEGooglePrebuilt
LOCAL_SRC_FILES := app/LatinIMEGooglePrebuilt/LatinIMEGooglePrebuilt.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

# Google Dialer
include $(CLEAR_VARS)
LOCAL_MODULE := GoogleDialer
LOCAL_SRC_FILES := app/GoogleDialer/GoogleDialer.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := true
include $(BUILD_PREBUILT)

# WIP- Untested
#include $(CLEAR_VARS)
#LOCAL_MODULE := IconPackVictorAndroid
#LOCAL_MODULE_TAGS := optional
#LOCAL_SRC_FILES := $(LOCAL_MODULE)/$(LOCAL_MODULE)Overlay.apk
#LOCAL_CERTIFICATE := PRESIGNED
#LOCAL_MODULE_CLASS := APPS
#LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
#LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay/
#LOCAL_PRODUCT_MODULE := true
#LOCAL_DEX_PREOPT := false
#LOCAL_OVERRIDES_PACKAGES := IconPackVictorAndroidOverlay
#include $(BUILD_PREBUILT)
